AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07d20571c32ba6cdc 
      SubnetId: subnet-04999e6284691e96f
      KeyName: cdpipeline
      Tags:
        - Key: env
          Value: github-actions
        - Key: Name
          Value: github-actions-server

  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: my-new-user
      Tags:
        - Key: Name
          Value: my-iam-user

Outputs:
  EC2InstancePublicIP:
    Description: "Public IP address of the EC2 instance"
    Value: !GetAtt 
      - MyEC2Instance
      - PublicIp
  IAMUserARN:
    Description: "ARN of the IAM user"
    Value: !Ref MyIAMUser
