AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-07d20571c32ba6cdc # Replace with a valid AMI ID for eu-west-2
      SubnetId: subnet-04999e6284691e96f
      KeyName: cdpipeline
      Tags:
        - Key: env
          Value: github-actions

  MyIAMUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: my-new-user
      Tags:
        - Key: Name
          Value: my-iam-user
