name: AWS CloudFormation Provisioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest # GitHub-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Linter install
        uses: scottbrenner/cfn-lint-action@v2
        with:
          command: cfn-lint -t./cloudformation-template.yaml

      - name: Set up AWS CLI
        run: |
          aws --version # Check AWS CLI version (GitHub-hosted runners should have it installed)

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-west-2

      - name: List Files
        run: ls -la

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file clouformation-template.yaml \
            --stack-name gactionststack \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
